version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.15.1
     
    working_directory: ~/repo
    steps:
      - checkout
      - newman/newman-run:
         collection: JSONPlaceholdercollection.json
workflows:
  version: 2
  postman collection:
    jobs:
      - newman-collection-run
